# Generated by Django 5.2.7 on 2025-10-22 14:45

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=180, unique=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="المسمى/اللقب المهني"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(blank=True, max_length=120, verbose_name="التخصص"),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="مثال: Django, REST, Tailwind",
                        max_length=400,
                        verbose_name="مهارات (مفصولة بفواصل)",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="نبذة مختصرة")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.employee_upload,
                        verbose_name="صورة",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="سعر الساعة (اختياري)",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم",
                    ),
                ),
                (
                    "public_visible",
                    models.BooleanField(default=True, verbose_name="ظهور عام"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "بروفايل موظف",
                "verbose_name_plural": "بروفايلات الموظفين",
                "indexes": [
                    models.Index(
                        fields=["public_visible", "rating"],
                        name="profiles_em_public__f46f7a_idx",
                    ),
                    models.Index(fields=["slug"], name="profiles_em_slug_efa368_idx"),
                ],
            },
        ),
    ]
