# Generated by Django 5.2.7 on 2025-10-31 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0003_alter_offer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone_id", models.IntegerField(blank=True, null=True)),
                (
                    "opener_role",
                    models.CharField(
                        choices=[
                            ("client", "عميل"),
                            ("employee", "موظف"),
                            ("admin", "إداري"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوح"),
                            ("in_review", "قيد المراجعة"),
                            ("resolved", "محسوم"),
                            ("canceled", "ملغى"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                ("details", models.TextField(blank=True)),
                ("resolved_note", models.TextField(blank=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="marketplace.request",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["open", "in_review"])),
                        fields=("request",),
                        name="uniq_open_dispute_per_request",
                    )
                ],
            },
        ),
    ]
