# Generated by Django 5.2.7 on 2025-10-31 18:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agreements", "0004_alter_agreementclauseitem_position_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "غير مدفوعة"),
                            ("paid", "مدفوعة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="unpaid",
                        max_length=16,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإصدار"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ السداد"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="طريقة السداد"
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع العملية"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="agreements.agreement",
                        verbose_name="الاتفاقية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="agreements.milestone",
                        verbose_name="الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة",
                "verbose_name_plural": "فواتير",
                "ordering": ["-issued_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "issued_at"],
                        name="finance_inv_status_64bdde_idx",
                    ),
                    models.Index(
                        fields=["agreement"], name="finance_inv_agreeme_825c61_idx"
                    ),
                ],
            },
        ),
    ]
