# Generated by Django 5.2.7 on 2025-11-01 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0006_agreement_agreement_total_amount_gte_0_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="موعد السداد"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأها",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الإصدار",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="فاتورة مرتبطة بمرحلة محددة (إن وُجدت). يُفضّل فاتورة واحدة لكل مرحلة.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="agreements.milestone",
                verbose_name="الدفعة",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="تاريخ السداد"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="ref_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="مرجع الدفع من بوابة/حوالة. غير فريد بالضرورة.",
                max_length=100,
                verbose_name="مرجع العملية",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["paid_at"], name="finance_inv_paid_at_3e9ead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["due_at"], name="finance_inv_due_at_9d0428_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("milestone__isnull", False)),
                fields=("milestone",),
                name="uniq_invoice_per_milestone",
            ),
        ),
    ]
