# Generated by Django 5.2.7 on 2025-10-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="العنوان")),
                ("details", models.TextField(blank=True, verbose_name="التفاصيل")),
                (
                    "estimated_duration_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="مدة تقديرية (أيام)"
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="سعر تقريبي",
                    ),
                ),
                (
                    "links",
                    models.TextField(blank=True, verbose_name="روابط مرتبطة (اختياري)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "طلب جديد"),
                            ("offer_selected", "تم اختيار عرض"),
                            ("agreement_pending", "اتفاقية بانتظار الموافقة"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("dispute", "نزاع"),
                            ("cancelled", "ملغى"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("has_milestones", models.BooleanField(default=False)),
                ("has_dispute", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests_as_employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_as_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص الملاحظة")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="رؤية مقيدة (داخلي)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="marketplace.note",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="marketplace.request",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص العرض")),
                (
                    "proposed_duration_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="مدة مقترحة (أيام)"
                    ),
                ),
                (
                    "proposed_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر مقترح"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "مقدَّم"),
                            ("selected", "مختار"),
                            ("rejected", "مرفوض"),
                        ],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="marketplace.request",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="marketplace_status_0b5e96_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "employee"),
                        name="unique_offer_per_employee_per_request",
                    )
                ],
            },
        ),
    ]
