# Generated by Django 5.2.7 on 2025-10-22 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ملاحظة",
                "verbose_name_plural": "ملاحظات",
            },
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={"verbose_name": "عرض", "verbose_name_plural": "عروض"},
        ),
        migrations.AlterModelOptions(
            name="request",
            options={"verbose_name": "طلب", "verbose_name_plural": "طلبات"},
        ),
        migrations.AddField(
            model_name="request",
            name="agreement_due_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="موعد استحقاق إرسال الاتفاقية"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="offer_selected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ اختيار العرض"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="sla_agreement_overdue",
            field=models.BooleanField(
                default=False, verbose_name="تجاوز مهلة إنشاء الاتفاقية (تم التنبيه؟)"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["request", "employee"], name="marketplace_request_199366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["status", "created_at"], name="marketplace_status_b3518a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["client"], name="marketplace_client__6e6a30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["assigned_employee"], name="marketplace_assigne_7cfd97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["agreement_due_at"], name="marketplace_agreeme_3f2065_idx"
            ),
        ),
    ]
