# Generated by Django 5.2.7 on 2025-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_note_options_alter_offer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="offer",
            name="unique_offer_per_employee_per_request",
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="marketplace_status_0b5e96_idx",
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="marketplace_request_199366_idx",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="text",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="offer",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_duration_days",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("selected", "العرض المختار"),
                    ("rejected", "مرفوض"),
                    ("withdrawn", "مسحوب"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
