# Generated by Django 5.2.7 on 2025-11-01 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_offer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "طلب جديد"),
                    ("offer_selected", "تم اختيار عرض"),
                    ("agreement_pending", "اتفاقية بانتظار الموافقة"),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "مكتمل"),
                    ("disputed", "نزاع"),
                    ("cancelled", "ملغى"),
                ],
                db_index=True,
                default="new",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "selected")),
                fields=("request",),
                name="uq_request_single_selected_offer",
            ),
        ),
    ]
