# Generated by Django 5.2.7 on 2025-10-22 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="أدخل أي صيغة (05 أو 00966 أو 966 أو +966). سيُحفظ دوليًا تلقائيًا.",
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\d\\+\\s\\-\\(\\)]{3,}$", "صيغة رقم غير صالحة."
                    )
                ],
                verbose_name="الجوال",
            ),
        ),
    ]
