# Generated by Django 5.2.7 on 2025-10-22 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_alter_note_options_alter_offer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="اتفاقية تنفيذ طلب",
                        max_length=180,
                        verbose_name="عنوان الاتفاقية",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص الاتفاقية النهائي")),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="المدة المتفق عليها (أيام)"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار موافقة العميل"),
                            ("accepted", "تمت الموافقة"),
                            ("rejected", "مرفوضة"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements_as_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements_as_employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement",
                        to="marketplace.request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=160, verbose_name="اسم الدفعة/المرحلة"),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف مختصر")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                (
                    "due_date_estimate",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق (تقديري)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التسليم"),
                            ("delivered", "تم التسليم"),
                            ("accepted", "مقبولة"),
                            ("rejected", "مرفوضة"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="الترتيب"),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="agreements.agreement",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
