# Generated by Django 5.2.7 on 2025-10-23 12:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0001_initial"),
        ("marketplace", "0002_alter_note_options_alter_offer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreement",
            options={"verbose_name": "اتفاقية", "verbose_name_plural": "اتفاقيات"},
        ),
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "دفعة",
                "verbose_name_plural": "دفعات",
            },
        ),
        migrations.RemoveField(
            model_name="agreement",
            name="client",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="description",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="due_date_estimate",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="name",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="status",
        ),
        migrations.AddField(
            model_name="agreement",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="سبب الرفض (إن وُجد)"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="milestone",
            name="due_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="مستحق بعد (أيام) من البداية"
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="title",
            field=models.CharField(
                default=1, max_length=160, verbose_name="عنوان الدفعة/المرحلة"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agreement",
            name="duration_days",
            field=models.PositiveIntegerField(default=7, verbose_name="المدة (أيام)"),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements_as_employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظف",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreement",
                to="marketplace.request",
                verbose_name="الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("pending", "بانتظار موافقة العميل"),
                    ("accepted", "تمت الموافقة"),
                    ("rejected", "مرفوضة"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="text",
            field=models.TextField(blank=True, verbose_name="نص الاتفاقية"),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان الاتفاقية"),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="الإجمالي (ريال)",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="agreements.agreement",
                verbose_name="الاتفاقية",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="المبلغ (ريال)"
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["status", "created_at"], name="agreements__status_9db6f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["employee"], name="agreements__employe_7d6320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["agreement", "order"], name="agreements__agreeme_292db7_idx"
            ),
        ),
    ]
