# Generated by Django 5.2.7 on 2025-10-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0002_alter_agreement_options_alter_milestone_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="معرف فريد (بالإنجليزية) للبند",
                        unique=True,
                        verbose_name="المعرف",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان البند")),
                ("body", models.TextField(verbose_name="نص البند")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل؟")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "بند اتفاقية",
                "verbose_name_plural": "بنود الاتفاقية",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="AgreementClauseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_text", models.TextField(blank=True, verbose_name="نص مخصص")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clause_items",
                        to="agreements.agreement",
                        verbose_name="الاتفاقية",
                    ),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agreements.agreementclause",
                        verbose_name="البند الجاهز",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند ضمن الاتفاقية",
                "verbose_name_plural": "بنود الاتفاقية المختارة",
                "ordering": ["position", "id"],
            },
        ),
    ]
