# Generated by Django 5.2.7 on 2025-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0003_agreementclause_agreementclauseitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementclauseitem",
            name="position",
            field=models.PositiveIntegerField(default=1, verbose_name="الترتيب"),
        ),
        migrations.AddConstraint(
            model_name="agreementclauseitem",
            constraint=models.UniqueConstraint(
                fields=("agreement", "position"),
                name="uniq_clauseitem_position_per_agreement",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                fields=("agreement", "order"), name="uniq_milestone_order_per_agreement"
            ),
        ),
    ]
