# Generated by Django 5.2.7 on 2025-10-31 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0004_alter_agreementclauseitem_position_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت الاعتماد"
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_milestones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمدت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت التسليم"
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="delivered_note",
            field=models.TextField(blank=True, verbose_name="ملاحظة التسليم"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت السداد"
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="rejected_reason",
            field=models.TextField(blank=True, verbose_name="سبب الرفض"),
        ),
        migrations.AddField(
            model_name="milestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد التنفيذ"),
                    ("delivered", "تم التسليم"),
                    ("approved", "معتمدة"),
                    ("rejected", "مرفوضة"),
                    ("paid", "مدفوعة"),
                ],
                default="pending",
                max_length=12,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="agreementclause",
            name="key",
            field=models.SlugField(
                help_text="معرف فريد (بالإنجليزية) للبند",
                unique=True,
                verbose_name="المعرّف الفريد",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["status"], name="agreements__status_3d9182_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["delivered_at"], name="agreements__deliver_45ac4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["approved_at"], name="agreements__approve_32f9fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["paid_at"], name="agreements__paid_at_a884ac_idx"
            ),
        ),
    ]
