# Generated by Django 5.2.7 on 2025-10-31 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0005_milestone_approved_at_milestone_approved_by_and_more"),
        ("marketplace", "0003_alter_offer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="agreement_total_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_days__gte", 1)),
                name="agreement_duration_days_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="milestone_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1)), name="milestone_order_gte_1"
            ),
        ),
    ]
